version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: django-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: react-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

