# Generated by Django 4.2.17 on 2024-12-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0003_user_is_active_user_is_staff_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("USER", "User")],
                default="USER",
                max_length=10,
            ),
        ),
    ]
